# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'many.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ManyWindow(object):
    def setupUi(self, ManyWindow):
        ManyWindow.setObjectName("ManyWindow")
        ManyWindow.resize(966, 519)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/window_icon/favicon-20191211100205340.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ManyWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(ManyWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(810, 390, 101, 80))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.ensure = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.ensure.setObjectName("ensure")
        self.verticalLayout_5.addWidget(self.ensure)
        self.begin_cal = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.begin_cal.setObjectName("begin_cal")
        self.verticalLayout_5.addWidget(self.begin_cal)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(670, 70, 54, 12))
        self.label_4.setObjectName("label_4")
        self.LineDisplayGB_Area = QtWidgets.QGroupBox(self.centralwidget)
        self.LineDisplayGB_Area.setGeometry(QtCore.QRect(340, 120, 261, 221))
        self.LineDisplayGB_Area.setObjectName("LineDisplayGB_Area")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(670, 100, 241, 241))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.label_14 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_14.setObjectName("label_14")
        self.verticalLayout.addWidget(self.label_14)
        self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(7)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.w_h = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.w_h.setObjectName("w_h")
        self.verticalLayout_2.addWidget(self.w_h)
        self.l_w = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.l_w.setObjectName("l_w")
        self.verticalLayout_2.addWidget(self.l_w)
        self.x0_y0_z0 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.x0_y0_z0.setObjectName("x0_y0_z0")
        self.verticalLayout_2.addWidget(self.x0_y0_z0)
        self.x_deta_y_deta_z_deta = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.x_deta_y_deta_z_deta.setObjectName("x_deta_y_deta_z_deta")
        self.verticalLayout_2.addWidget(self.x_deta_y_deta_z_deta)
        self.direction_num = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.direction_num.setObjectName("direction_num")
        self.verticalLayout_2.addWidget(self.direction_num)
        self.yuzhi = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.yuzhi.setObjectName("yuzhi")
        self.verticalLayout_2.addWidget(self.yuzhi)
        self.scal_number = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.scal_number.setObjectName("scal_number")
        self.verticalLayout_2.addWidget(self.scal_number)
        self.te_zheng = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.te_zheng.setObjectName("te_zheng")
        self.verticalLayout_2.addWidget(self.te_zheng)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.LineDisplayGB_Volume = QtWidgets.QGroupBox(self.centralwidget)
        self.LineDisplayGB_Volume.setGeometry(QtCore.QRect(50, 120, 261, 221))
        self.LineDisplayGB_Volume.setObjectName("LineDisplayGB_Volume")
        self.zu_name = QtWidgets.QLabel(self.centralwidget)
        self.zu_name.setGeometry(QtCore.QRect(180, 360, 591, 78))
        self.zu_name.setObjectName("zu_name")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(50, 440, 571, 20))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 360, 111, 78))
        self.label_2.setObjectName("label_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(50, 20, 501, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_zu_path = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_zu_path.setObjectName("label_zu_path")
        self.horizontalLayout.addWidget(self.label_zu_path)
        self.lineEdit_zu_path = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_zu_path.setReadOnly(False)
        self.lineEdit_zu_path.setObjectName("lineEdit_zu_path")
        self.horizontalLayout.addWidget(self.lineEdit_zu_path)
        self.pushButton_zu_path = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_zu_path.setObjectName("pushButton_zu_path")
        self.horizontalLayout.addWidget(self.pushButton_zu_path)
        ManyWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ManyWindow)
        self.statusbar.setObjectName("statusbar")
        ManyWindow.setStatusBar(self.statusbar)
        self.zu_path = QtWidgets.QAction(ManyWindow)
        self.zu_path.setObjectName("zu_path")

        self.retranslateUi(ManyWindow)
        self.ensure.clicked.connect(ManyWindow.ensure)
        self.begin_cal.clicked.connect(ManyWindow.begin)
        self.pushButton_zu_path.clicked.connect(ManyWindow.file_dir)
        QtCore.QMetaObject.connectSlotsByName(ManyWindow)

    def retranslateUi(self, ManyWindow):
        _translate = QtCore.QCoreApplication.translate
        ManyWindow.setWindowTitle(_translate("ManyWindow", "火焰三维瞬态特征分析软件-批量火焰图像处理"))
        self.ensure.setText(_translate("ManyWindow", "确定参数"))
        self.begin_cal.setText(_translate("ManyWindow", "开始计算"))
        self.label_4.setText(_translate("ManyWindow", "参数设置"))
        self.LineDisplayGB_Area.setTitle(_translate("ManyWindow", "表面积/m2"))
        self.label_5.setText(_translate("ManyWindow", "棋盘规格（x/y）"))
        self.label_6.setText(_translate("ManyWindow", "图片尺寸（长/宽）"))
        self.label_7.setText(_translate("ManyWindow", "三维起始点"))
        self.label_8.setText(_translate("ManyWindow", "三维步长"))
        self.label_9.setText(_translate("ManyWindow", "方向数目"))
        self.label_14.setText(_translate("ManyWindow", "阈值"))
        self.label_10.setText(_translate("ManyWindow", "比例尺"))
        self.label.setText(_translate("ManyWindow", "实验文件夹特征"))
        self.w_h.setText(_translate("ManyWindow", "6/9"))
        self.l_w.setText(_translate("ManyWindow", "1920/1200"))
        self.x0_y0_z0.setText(_translate("ManyWindow", "-5/5/-4/80/-5/5"))
        self.x_deta_y_deta_z_deta.setText(_translate("ManyWindow", "30/150/30"))
        self.direction_num.setText(_translate("ManyWindow", "3"))
        self.yuzhi.setText(_translate("ManyWindow", "10"))
        self.scal_number.setText(_translate("ManyWindow", "1"))
        self.te_zheng.setText(_translate("ManyWindow", "kw"))
        self.LineDisplayGB_Volume.setTitle(_translate("ManyWindow", "体积/m3"))
        self.zu_name.setText(_translate("ManyWindow", "0"))
        self.label_2.setText(_translate("ManyWindow", "组序号/组名/方向"))
        self.label_zu_path.setText(_translate("ManyWindow", "火焰文件所在路径"))
        self.lineEdit_zu_path.setText(_translate("ManyWindow", "C:/Users/yhstc/Desktop/90"))
        self.pushButton_zu_path.setText(_translate("ManyWindow", "选择"))
        self.zu_path.setText(_translate("ManyWindow", "打开"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ManyWindow = QtWidgets.QMainWindow()
    ui = Ui_ManyWindow()
    ui.setupUi(ManyWindow)
    ManyWindow.show()
    sys.exit(app.exec_())
